appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: n10fNUigiYudL9BEK4tKlPdkid0ZUO/R8VqAEIZK0MDf2Idlzvbn6KnQZjDqisIBCYXb63eHqvuNjWuAROyfBSrOfbxIQmMO0Xvci59M/cXXkl/qNVXqyY55RscAEbcwU+U1+QN2e7gIm6UpMU8wZsIiCi3j38y8xy158bDvgVwD2YHJTk/xaxj0D1fdHsQxr3gc1pj965dyRtbZk0OC0UHz04Fi70rSAJ7I+xCHEoYHdZEfxcz+nZ0MpCi4gjHWTT6Z6QSqp4wyzzqxfHp+BGy2F0rv6JvQPwuThbvue/ssPsTSMKWvsgAnVS3v43SwsI0epnCvx8/3ERpaFRRQ4sazIPP+Z+sPCtsF1hcgQzE2R660oMOGrpxsTRJcCBEYn9EyiNhwYrTRWVQTsQdl56UsvfIpRPbcqOmGwU2LSYxAC6Dq1Fg/DR39G0ztaxePOD8lI6IdstsKEu1E+n7RUNU33JsF5BuY/FIf4Fyg9TjtVYCTpdmdauByU7KedFGuRMTPWS+6dSGFgKvnuYxUjZr78E8NDgYhK4ygoQ11SaDM5HHkEcNuPdOynKO/lto4NQLXNsG6CC6PkTGYoQWsYS63GFpsCu06HB65x+N4+A0AWV5+yN7dRx7yTcoHjTry5y9WoxHeeObz3E1nUqupID1uyifOoUEIwLv8dSu1OKs=}
